<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../public/css/style.css" />
    <title>Welcome to 3WA MVC Framework</title>
  </head>
  <body>
      <header>
        <section>
            <nav id="menu" class="dekstop">
                <ul>
                    <li><a href="../controller/welcome.php">Accueil</a></li>
                    <li><a href="#">Zombies</a></li>
                    <li><a href="#">Plantes</a></li>
                    <li><a href="../controller/contact.php">Contact</a></li>
                </ul>
            </nav>
        </section>
    </header>
    <main>
         {{ content }}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

